"""The append-only JSONL trace: the source of truth for a run.

Every model call, routing decision, policy check, approval, and tool call is
written here, one event per line, flushed per event so a crash never loses
earlier steps.
"""

from __future__ import annotations

from wicklight.trace.events import (
    TRACE_FORMAT_VERSION,
    ApprovalRequested,
    ApprovalRequestedPayload,
    ApprovalResolved,
    ApprovalResolvedPayload,
    ContextBuilt,
    ContextBuiltPayload,
    Decision,
    ErrorEvent,
    ErrorPayload,
    LimitHit,
    LimitHitPayload,
    ModelCalled,
    ModelCalledPayload,
    ModelResponded,
    ModelRespondedPayload,
    ModelRouted,
    ModelRoutedPayload,
    PolicyChecked,
    PolicyCheckedPayload,
    RunFinished,
    RunFinishedPayload,
    RunStarted,
    RunStartedPayload,
    RunStatus,
    ToolExecuted,
    ToolExecutedPayload,
    ToolProposed,
    ToolProposedPayload,
    TraceEvent,
    dump_trace_event,
    parse_trace_event,
    trace_event_adapter,
)
from wicklight.trace.writer import (
    DEFAULT_BLOB_THRESHOLD,
    Redactor,
    TraceWriter,
)

__all__ = [
    "DEFAULT_BLOB_THRESHOLD",
    "TRACE_FORMAT_VERSION",
    "ApprovalRequested",
    "ApprovalRequestedPayload",
    "ApprovalResolved",
    "ApprovalResolvedPayload",
    "ContextBuilt",
    "ContextBuiltPayload",
    "Decision",
    "ErrorEvent",
    "ErrorPayload",
    "LimitHit",
    "LimitHitPayload",
    "ModelCalled",
    "ModelCalledPayload",
    "ModelResponded",
    "ModelRespondedPayload",
    "ModelRouted",
    "ModelRoutedPayload",
    "PolicyChecked",
    "PolicyCheckedPayload",
    "Redactor",
    "RunFinished",
    "RunFinishedPayload",
    "RunStarted",
    "RunStartedPayload",
    "RunStatus",
    "ToolExecuted",
    "ToolExecutedPayload",
    "ToolProposed",
    "ToolProposedPayload",
    "TraceEvent",
    "TraceWriter",
    "dump_trace_event",
    "parse_trace_event",
    "trace_event_adapter",
]
